### PR TITLE
Retrospectively re-update MSC2403 to clarify that invite->knock is *not* legal.

### PR DESCRIPTION
**Pull request by kegsay**
Reverts https://github.com/matrix-org/matrix-spec-proposals/pull/3850

See https://github.com/matrix-org/matrix-spec/pull/1717

Rationale: https://github.com/matrix-org/matrix-spec/issues/1710

### CODE REVIEW

**Comment by richvdh** [comment]
For links: this updates #2403.

**Review by richvdh — APPROVED** [review]
This LGTM, but in the spirit of us having royally fscked this up in the past, maybe others would like to weigh in and double-check?

**Review by dbkr — APPROVED** [review]
Seems good, thanks for wading through this and getting it sorted!

**Pull request merged**
